export const skillTags = [
  {
    value: "programming",
    subtags: [
      { value: "javascript" },
      { value: "python" },
      { value: "ruby" },
      { value: "golang" },
      { value: "rust" },
      { value: "Erlang" },
      { value: "C++" },
      {
        value: "frontend",
        subtags: ["react", "nextjs", "vue", "nuxt.js", "angular", "graphql"],
      },
      {
        value: "backend",
        subtags: [
          "node.js",
          "ruby on rails",
          "django",
          "laravel",
          "spring",
          "express.js",
          "Elixir",
          "flask",
          "symfony",
          "ASP.NET",
          "Phoenix",
          "graphql",
          "gRPC",
        ],
      },
      {
        value: "fullstack",
        subtags: [
          "software engineering",
          "systems architecture",
          "devops",
          "agile methodologies",
          "database design",
          "security engineering",
          "performance optimization",
          "data modeling",
          "testing and test automation",
          "project management",
        ],
      },
      {
        value: "data",
        subtags: ["data analysis", "data engineering", "machine learning"],
      },
      {
        value: "security",
        subtags: ["application security", "network security", "encryption"],
      },
      {
        value: "mobile",
        subtags: ["android development", "ios development", "react native"],
      },
      {
        value: "game development",
        subtags: ["unity", "unreal engine", "game design"],
      },
      {
        value: "blockchain",
        subtags: ["smart contracts", "distributed systems", "crypto"],
      },
      {
        value: "testing",
        subtags: ["unit testing", "integration testing", "test automation"],
      },
    ],
  },

  {
    value: "engineering",
    subtags: [
      {
        value: "mechanical",
        subtags: [
          "thermodynamics",
          "fluid mechanics",
          "solid mechanics",
          "mechatronics",
          "manufacturing processes",
          "robotics",
          "machine design",
        ],
      },
      {
        value: "civil",
        subtags: [
          "structural",
          "geotechnical",
          "transportation",
          "water resources",
          "environmental",
          "construction",
          "urban planning",
        ],
      },
      {
        value: "electrical",
        subtags: [
          "circuit theory",
          "power systems",
          "electromagnetics",
          "electronics",
          "control systems",
          "digital signal processing",
          "telecommunications",
        ],
      },
      {
        value: "chemical",
        subtags: [
          "process design",
          "thermodynamics",
          "chemical kinetics",
          "transport phenomena",
          "separation processes",
          "material science",
          "biomedical",
        ],
      },
      {
        value: "computer",
        subtags: [
          "computer hardware design",
          "computer software design",
          "embedded systems",
          "computer networks",
          "cybersecurity",
          "artificial intelligence",
          "human-computer interaction",
        ],
      },
      {
        value: "aerospace",
        subtags: [
          "aerodynamics",
          "propulsion",
          "flight mechanics",
          "materials science",
          "structural design",
          "avionics",
          "spacecraft",
        ],
      },
      {
        value: "biomedical",
        subtags: [
          "biomechanics",
          "biomaterials",
          "medical devices",
          "physiology",
          "medical imaging",
          "rehabilitation",
          "bioinformatics",
        ],
      },
      {
        value: "environmental",
        subtags: [
          "water and wastewater treatment",
          "air pollution control",
          "hazardous waste management",
          "ecological",
          "sustainability",
          "environmental policy",
          "climate change mitigation",
        ],
      },
      {
        value: "materials",
        subtags: [
          "materials science",
          "materials processing",
          "metallurgy",
          "ceramics",
          "polymer",
          "nanotechnology",
          "energy materials",
        ],
      },
    ],
  },
  {
    value: "science",
    subtags: [
      {
        value: "biology",
        subtags: [
          "microbiology",
          "molecular biology",
          "genetics",
          "ecology",
          "evolution",
          "physiology",
        ],
      },
      {
        value: "chemistry",
        subtags: [
          "organic chemistry",
          "inorganic chemistry",
          "physical chemistry",
          "analytical chemistry",
          "biochemistry",
        ],
      },
      {
        value: "physics",
        subtags: [
          "classical mechanics",
          "electromagnetism",
          "thermodynamics",
          "quantum mechanics",
          "astrophysics",
          "particle physics",
          "condensed matter physics",
        ],
      },
      {
        value: "earth science",
        subtags: ["geology", "oceanography", "meteorology", "climatology"],
      },
      {
        value: "mathematics",
        subtags: [
          "algebra",
          "calculus",
          "geometry",
          "statistics",
          "probability theory",
        ],
      },
      {
        value: "computer science",
        subtags: [
          "algorithms",
          "data structures",
          "machine learning",
          "artificial intelligence",
          "computer vision",
          "natural language processing",
          "human-computer interaction",
        ],
      },
      {
        value: "environmental science",
        subtags: [
          "environmental policy",
          "conservation biology",
          "ecosystem management",
          "sustainability",
          "environmental chemistry",
        ],
      },
      {
        value: "medical science",
        subtags: [
          "anatomy",
          "physiology",
          "pharmacology",
          "pathology",
          "epidemiology",
          "public health",
        ],
      },
      {
        value: "social science",
        subtags: [
          "psychology",
          "sociology",
          "economics",
          "political science",
          "anthropology",
        ],
      },
    ],
  },
  {
    value: "product",
    subtags: [
      {
        value: "product management",
        subtags: ["product strategy", "roadmapping", "user research"],
      },
      { value: "project management", subtags: ["agile", "scrum", "kanban"] },
      {
        value: "marketing",
        subtags: ["seo", "social media", "content marketing"],
      },
      {
        value: "sales",
        subtags: ["lead generation", "pipeline management", "closing deals"],
      },
      {
        value: "customer support",
        subtags: ["troubleshooting", "ticket management", "customer success"],
      },
      {
        value: "analytics",
        subtags: ["google analytics", "mixpanel", "kissmetrics"],
      },
      {
        value: "business development",
        subtags: ["partnerships", "new market entry", "go-to-market strategy"],
      },
      {
        value: "finance",
        subtags: ["budgeting", "forecasting", "financial modeling"],
      },
    ],
  },
  {
    value: "design",
    subtags: [
      {
        value: "graphic design",
        subtags: ["branding", "typography", "print design"],
      },
      {
        value: "digital design",
        subtags: ["web design", "app design", "ui design", "ux design"],
      },
      {
        value: "motion design",
        subtags: ["animation", "video production", "3d design"],
      },
      {
        value: "product design",
        subtags: ["user-centered design", "design thinking", "prototyping"],
      },
      {
        value: "game design",
        subtags: ["game mechanics", "game balancing", "level design"],
      },
      {
        value: "visual design",
        subtags: ["icon design", "infographic design", "data visualization"],
      },
    ],
  },

  {
    value: "art",
    subtags: [
      {
        value: "visual art",
        subtags: [
          "drawing",
          "painting",
          "printmaking",
          "photography",
          "sculpture",
          "installation art",
          "digital art",
        ],
      },
      {
        value: "performing art",
        subtags: [
          "music",
          "dance",
          "theatre",
          "opera",
          "circus",
          "comedy",
          "magic",
        ],
      },
      {
        value: "design",
        subtags: [
          "graphic design",
          "product design",
          "fashion design",
          "interior design",
          "landscape design",
          "industrial design",
          "game design",
        ],
      },
      {
        value: "film and video",
        subtags: [
          "film production",
          "animation",
          "cinematography",
          "film editing",
          "screenwriting",
          "documentary",
          "experimental film",
        ],
      },
      {
        value: "art history and theory",
        subtags: [
          "art movements",
          "aesthetics",
          "critical theory",
          "cultural studies",
          "museum studies",
          "curatorial studies",
          "conservation and restoration",
        ],
      },
      {
        value: "crafts",
        subtags: [
          "ceramics",
          "textile art",
          "woodworking",
          "metalworking",
          "jewelry making",
          "bookbinding",
          "paper art",
        ],
      },
      {
        value: "architecture",
        subtags: [
          "architectural design",
          "landscape architecture",
          "urban design",
          "sustainable architecture",
          "historical preservation",
          "interior architecture",
          "building technology",
        ],
      },
      {
        value: "art education",
        subtags: [
          "teaching techniques",
          "pedagogy",
          "curriculum design",
          "assessment and evaluation",
          "technology integration",
          "arts integration",
          "teacher professional development",
        ],
      },
      {
        value: "public art and community engagement",
        subtags: [
          "social practice art",
          "participatory art",
          "community-based art",
          "street art",
          "public installations",
          "civic engagement",
          "cultural diplomacy",
        ],
      },
    ],
  },
  {
    value: "business",
    subtags: [
      {
        value: "finance",
        subtags: [
          "financial analysis",
          "investment banking",
          "asset management",
          "corporate finance",
          "personal finance",
          "risk management",
          "financial modeling",
        ],
      },
      {
        value: "marketing",
        subtags: [
          "digital marketing",
          "branding",
          "market research",
          "social media marketing",
          "product management",
          "sales",
          "public relations",
        ],
      },
      {
        value: "management",
        subtags: [
          "organizational behavior",
          "human resources",
          "operations management",
          "project management",
          "strategic management",
          "supply chain management",
          "leadership",
        ],
      },
      {
        value: "entrepreneurship",
        subtags: [
          "business planning",
          "startup development",
          "market analysis",
          "customer development",
          "funding and financing",
          "pitching and presenting",
          "growth strategies",
        ],
      },
      {
        value: "accounting",
        subtags: [
          "financial accounting",
          "managerial accounting",
          "taxation",
          "auditing",
          "bookkeeping",
          "cost accounting",
          "forensic accounting",
        ],
      },
      {
        value: "e-commerce",
        subtags: [
          "online marketplaces",
          "payment systems",
          "logistics and shipping",
          "customer experience",
          "e-commerce analytics",
          "e-commerce strategy",
          "e-commerce platform development",
        ],
      },
      {
        value: "international business",
        subtags: [
          "global trade",
          "cross-cultural management",
          "international finance",
          "international marketing",
          "international law",
          "global supply chain management",
          "international negotiations",
        ],
      },
      {
        value: "business ethics",
        subtags: [
          "corporate social responsibility",
          "ethical decision-making",
          "business law and regulations",
          "sustainability and environmental ethics",
          "social justice and equity",
          "ethical leadership",
          "ethics in finance and accounting",
        ],
      },
      {
        value: "innovation and design thinking",
        subtags: [
          "design thinking methodologies",
          "user-centered design",
          "prototyping and testing",
          "open innovation",
          "product innovation",
          "service innovation",
          "lean startup methodologies",
        ],
      },
    ],
  },

  {
    value: "legal",
    subtags: [
      {
        value: "substantive law",
        subtags: [
          "criminal law",
          "civil law",
          "corporate law",
          "employment law",
          "intellectual property law",
          "real estate law",
          "tax law",
        ],
      },
      {
        value: "procedural law",
        subtags: [
          "civil procedure",
          "criminal procedure",
          "evidence",
          "appellate practice",
          "alternative dispute resolution",
          "mediation and negotiation",
          "arbitration",
        ],
      },
      {
        value: "legal research and writing",
        subtags: [
          "legal research methods",
          "legal writing and analysis",
          "legal drafting",
          "brief writing and advocacy",
          "contract drafting and negotiation",
          "persuasion and argumentation",
          "communication skills for lawyers",
        ],
      },
      {
        value: "law practice management",
        subtags: [
          "law firm management",
          "law office technology",
          "billing and financial management",
          "client relations and marketing",
          "project management",
          "time management and productivity",
          "professional ethics and responsibility",
        ],
      },
      {
        value: "specialized areas of law",
        subtags: [
          "international law",
          "environmental law",
          "health law",
          "family law",
          "immigration law",
          "bankruptcy law",
          "entertainment law",
        ],
      },
      {
        value: "judicial process",
        subtags: [
          "judicial decision-making",
          "judicial ethics",
          "appellate practice",
          "judicial opinion writing",
          "judicial selection and appointment",
          "judicial review",
          "legal interpretation and construction",
        ],
      },
      {
        value: "legal systems and institutions",
        subtags: [
          "comparative law",
          "constitutional law",
          "administrative law",
          "regulatory law",
          "the legal profession",
          "the judiciary",
          "the legislative process",
        ],
      },
      {
        value: "dispute resolution",
        subtags: [
          "mediation and negotiation",
          "arbitration",
          "litigation",
          "pre-trial practice",
          "trial practice",
          "settlement negotiation",
          "enforcement of judgments",
        ],
      },
      {
        value: "advocacy and lawyering skills",
        subtags: [
          "client counseling",
          "trial advocacy",
          "deposition skills",
          "oral argument",
          "mock trial participation",
          "negotiation and settlement",
          "dispute resolution and conflict management",
        ],
      },
    ],
  },
  {
    value: "policymaking",
    subtags: [
      {
        value: "research and analysis",
        subtags: [
          "data analysis",
          "qualitative research methods",
          "quantitative research methods",
          "policy analysis",
          "cost-benefit analysis",
          "survey design and analysis",
          "program evaluation",
        ],
      },
      {
        value: "policy development",
        subtags: [
          "policy formulation",
          "policy implementation",
          "policy evaluation",
          "policy advocacy",
          "stakeholder engagement",
          "policy negotiation and compromise",
          "public opinion analysis",
        ],
      },
      {
        value: "political processes",
        subtags: [
          "electoral systems",
          "campaign strategy and tactics",
          "legislative processes",
          "lobbying and advocacy",
          "media relations",
          "political parties and interest groups",
          "public administration and bureaucracy",
        ],
      },
      {
        value: "public policy domains",
        subtags: [
          "economic policy",
          "education policy",
          "environmental policy",
          "foreign policy",
          "health policy",
          "housing policy",
          "social policy",
        ],
      },
      {
        value: "policy tools and instruments",
        subtags: [
          "regulatory policy",
          "fiscal policy",
          "monetary policy",
          "tax policy",
          "public-private partnerships",
          "government procurement",
          "public service delivery",
        ],
      },
      {
        value: "international policy",
        subtags: [
          "global governance",
          "international law",
          "diplomacy and negotiation",
          "human rights",
          "security and defense",
          "international development",
          "multilateral institutions",
        ],
      },
      {
        value: "policy communication and dissemination",
        subtags: [
          "policy briefs",
          "policy memos",
          "media relations",
          "public relations",
          "public speaking and presentation skills",
          "social media and digital outreach",
          "journalistic writing",
        ],
      },
      {
        value: "policy ethics and values",
        subtags: [
          "democratic values",
          "social justice and equity",
          "ethical decision-making",
          "human rights",
          "environmental sustainability",
          "corporate social responsibility",
          "transparency and accountability",
        ],
      },
      {
        value: "policy implementation and management",
        subtags: [
          "organizational behavior",
          "public management",
          "performance management",
          "budgeting and financial management",
          "program design and implementation",
          "capacity building and training",
          "risk management",
        ],
      },
    ],
  },
];
